/**
 * Questions loader — fetches pre-generated JSON problem files from public/questions/.
 *
 * Problem files are generated by AI (Claude Code / Claude agent) and saved as JSON.
 * The frontend only reads these files; no network/API calls to AI are made at runtime.
 *
 * Directory structure (under public/questions/):
 *   toefl/reading/complete-words/      *.json
 *   toefl/reading/daily-life/          *.json
 *   toefl/reading/academic/            *.json
 *   toefl/writing/build-sentence/      *.json
 *   toefl/writing/email/               *.json
 *   toefl/writing/discussion/          *.json
 *   toefl/speaking/listen-repeat/      *.json
 *   toefl/speaking/interview/          *.json
 *   toeic/part5/                       *.json
 *   toeic/part6/                       *.json
 *   toeic/part7/                       *.json
 *
 * Each directory has an index.json listing available files:
 *   { "files": ["001.json", "20261007-library-hours.json", ...] }
 * It is generated from the directory contents (see vite.config.ts), so
 * adding or deleting a file is all it takes.
 *
 * A file's basename is the problem's ID: stored attempts point at it, so it
 * must never change or be reused. Display numbers are just list positions.
 */

export interface QuestionIndex {
  files: string[];
}

export interface LoadedQuestion<T> {
  data: T;
  file: string;
}

export interface QuestionFileEntry {
  file: string;
  id: string;
}

const QUESTION_ID = /^[a-z0-9-]+$/i;

export function questionIdFromFile(file: string): string {
  return file.replace(/\.json$/i, "");
}

export async function fetchQuestionIndex(
  taskPath: string,
): Promise<QuestionIndex> {
  const res = await fetch(`/questions/${taskPath}/index.json`);
  if (!res.ok)
    throw new Error(`No questions found for ${taskPath}. Generate some first!`);
  return res.json();
}

export async function fetchRandomQuestion<T>(taskPath: string): Promise<T> {
  const loaded = await fetchRandomQuestionWithMeta<T>(taskPath);
  return loaded.data;
}

export async function listQuestionFiles(
  taskPath: string,
): Promise<QuestionFileEntry[]> {
  const index = await fetchQuestionIndex(taskPath);
  // Plain code-unit order, so `>` on IDs agrees with list order.
  return index.files
    .map((file) => ({ file, id: questionIdFromFile(file) }))
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

export async function fetchQuestionByFileWithMeta<T>(
  taskPath: string,
  file: string,
): Promise<LoadedQuestion<T>> {
  const res = await fetch(`/questions/${taskPath}/${file}`);
  if (!res.ok) throw new Error(`Failed to load question file: ${file}`);
  const data = (await res.json()) as T;
  return { data, file };
}

export async function fetchQuestionByIdWithMeta<T>(
  taskPath: string,
  id: string,
): Promise<LoadedQuestion<T>> {
  if (!QUESTION_ID.test(id)) {
    throw new Error(`Invalid question ID "${id}".`);
  }
  return fetchQuestionByFileWithMeta<T>(taskPath, `${id}.json`);
}

export async function fetchRandomQuestionWithMeta<T>(
  taskPath: string,
): Promise<LoadedQuestion<T>> {
  const files = await listQuestionFiles(taskPath);
  if (files.length === 0) {
    throw new Error(`No question files in ${taskPath}. Generate some first!`);
  }
  const selected = files[Math.floor(Math.random() * files.length)];
  return fetchQuestionByFileWithMeta<T>(taskPath, selected.file);
}

export async function fetchAllQuestions<T>(taskPath: string): Promise<T[]> {
  const index = await fetchQuestionIndex(taskPath);
  const results = await Promise.all(
    index.files.map(async (file) => {
      const res = await fetch(`/questions/${taskPath}/${file}`);
      if (!res.ok) throw new Error(`Failed to load: ${file}`);
      return res.json() as Promise<T>;
    }),
  );
  return results;
}
