/**
 * Questions loader — fetches pre-generated JSON problem files from public/questions/.
 *
 * Problem files are generated by AI (Claude Code / Claude agent) and saved as JSON.
 * The frontend only reads these files; no network/API calls to AI are made at runtime.
 *
 * Directory structure (under public/questions/):
 *   toefl/reading/complete-words/      *.json
 *   toefl/reading/daily-life/          *.json
 *   toefl/reading/academic/            *.json
 *   toefl/writing/build-sentence/      *.json
 *   toefl/writing/email/               *.json
 *   toefl/writing/discussion/          *.json
 *   toefl/speaking/listen-repeat/      *.json
 *   toefl/speaking/interview/          *.json
 *   toeic/part5/                       *.json
 *   toeic/part6/                       *.json
 *   toeic/part7/                       *.json
 *
 * Each directory has an index.json listing available files:
 *   { "files": ["001.json", "002.json", ...] }
 */

export interface QuestionIndex {
  files: string[];
}

export interface LoadedQuestion<T> {
  data: T;
  file: string;
}

import type { TaskId } from "../hooks/useScoreHistory";

export interface QuestionFileEntry {
  file: string;
  number: number;
}

export async function fetchQuestionIndex(
  taskPath: string,
): Promise<QuestionIndex> {
  const res = await fetch(`/questions/${taskPath}/index.json`);
  if (!res.ok)
    throw new Error(`No questions found for ${taskPath}. Generate some first!`);
  return res.json();
}

export async function fetchRandomQuestion<T>(taskPath: string): Promise<T> {
  const loaded = await fetchRandomQuestionWithMeta<T>(taskPath);
  return loaded.data;
}

export async function listQuestionFiles(
  taskPath: string,
): Promise<QuestionFileEntry[]> {
  const index = await fetchQuestionIndex(taskPath);
  return index.files
    .map((file) => {
      const basename = file.replace(/\.[^.]+$/, "");
      if (!/^\d+$/.test(basename)) {
        throw new Error(
          `Question file "${file}" in ${taskPath} must use numeric filename like 001.json.`,
        );
      }
      return {
        file,
        number: Number.parseInt(basename, 10),
      };
    })
    .sort((a, b) => a.number - b.number || a.file.localeCompare(b.file));
}

export async function fetchQuestionByFileWithMeta<T>(
  taskPath: string,
  file: string,
): Promise<LoadedQuestion<T>> {
  const res = await fetch(`/questions/${taskPath}/${file}`);
  if (!res.ok) throw new Error(`Failed to load question file: ${file}`);
  const data = (await res.json()) as T;
  return { data, file };
}

export async function fetchQuestionByNumberWithMeta<T>(
  taskPath: string,
  questionNumber: number,
): Promise<LoadedQuestion<T>> {
  const files = await listQuestionFiles(taskPath);
  const selected = files.find((item) => item.number === questionNumber);
  if (!selected) {
    throw new Error(
      `Question ${questionNumber} not found in ${taskPath}. Generate or register it first.`,
    );
  }
  return fetchQuestionByFileWithMeta<T>(taskPath, selected.file);
}

export async function fetchRandomQuestionWithMeta<T>(
  taskPath: string,
): Promise<LoadedQuestion<T>> {
  const files = await listQuestionFiles(taskPath);
  if (files.length === 0) {
    throw new Error(`No question files in ${taskPath}. Generate some first!`);
  }
  const selected = files[Math.floor(Math.random() * files.length)];
  return fetchQuestionByFileWithMeta<T>(taskPath, selected.file);
}

export async function fetchAllQuestions<T>(taskPath: string): Promise<T[]> {
  const index = await fetchQuestionIndex(taskPath);
  const results = await Promise.all(
    index.files.map(async (file) => {
      const res = await fetch(`/questions/${taskPath}/${file}`);
      if (!res.ok) throw new Error(`Failed to load: ${file}`);
      return res.json() as Promise<T>;
    }),
  );
  return results;
}

function hasKey(data: unknown, key: string): data is Record<string, unknown> {
  return data != null && typeof data === "object" && key in data;
}

function getArray(data: unknown, key: string): unknown[] | null {
  if (!hasKey(data, key)) return null;
  const value = data[key];
  return Array.isArray(value) ? value : null;
}

function countArray(data: unknown, key: string): number | null {
  const arr = getArray(data, key);
  return arr ? arr.length : null;
}

function sumNestedQuestions(data: unknown, outerKey: string): number | null {
  const outer = getArray(data, outerKey);
  if (!outer) return null;
  return outer.reduce<number>((sum, item) => {
    const questions = getArray(item, "questions");
    return sum + (questions ? questions.length : 0);
  }, 0);
}

type CountExtractor = (data: unknown) => number | null;

/**
 * Explicit registry of how to extract the question/item count from a task's
 * question file. Keeping this table explicit avoids brittle structural
 * reflection and makes each task's shape assumption readable in one place.
 */
const TASK_QUESTION_COUNT_EXTRACTORS: Record<TaskId, CountExtractor> = {
  "toefl/reading/complete-words": (d) => countArray(d, "items"),
  "toefl/reading/daily-life": (d) => sumNestedQuestions(d, "texts"),
  "toefl/reading/academic": (d) => countArray(d, "questions"),
  "toefl/listening/conversation": (d) => countArray(d, "questions"),
  "toefl/listening/lecture": (d) => countArray(d, "questions"),
  "toefl/listening/response": (d) => countArray(d, "questions"),
  "toefl/listening/announcement": (d) => countArray(d, "questions"),
  "toefl/writing/build-sentence": (d) => countArray(d, "sentences"),
  "toefl/writing/email": () => 1,
  "toefl/writing/discussion": () => 1,
  "toefl/speaking/listen-repeat": (d) => countArray(d, "sentences"),
  "toefl/speaking/interview": (d) => countArray(d, "questions"),
  "toeic/part2": (d) => countArray(d, "questions"),
  "toeic/part3": (d) => countArray(d, "questions"),
  "toeic/part4": (d) => countArray(d, "questions"),
  "toeic/part5": (d) => countArray(d, "questions"),
  "toeic/part6": (d) => sumNestedQuestions(d, "passages"),
  "toeic/part7": (d) => countArray(d, "questions"),
  shadowing: (d) => countArray(d, "sentences"),
};

/**
 * Inspects the first available question file for a task and returns the number
 * of questions (or items/prompts) it contains. Returns `null` when no files
 * are available or the task is not registered.
 */
export async function fetchTaskQuestionCount(
  taskId: TaskId,
): Promise<number | null> {
  const extractor = TASK_QUESTION_COUNT_EXTRACTORS[taskId];
  if (!extractor) return null;

  const files = await listQuestionFiles(taskId);
  if (files.length === 0) return null;
  const first = files[0];
  if (!first) return null;

  const loaded = await fetchQuestionByFileWithMeta<unknown>(
    taskId,
    first.file,
  );
  return extractor(loaded.data);
}
