import { useNavigate } from "react-router-dom";
import { Button } from "../components/ui/Button";
import styles from "./HomePage.module.css";

export function HomePage() {
  const navigate = useNavigate();
  return (
    <div className={styles.page}>
      <div className={styles.hero}>
        <h1 className={styles.title}>English Test Practice</h1>
        <p className={styles.description}>
          Practice with question JSON generated by AI agents. Supports the TOEFL
          iBT 2026 format and TOEIC Reading.
        </p>
      </div>

      <div className={styles.cards}>
        <div className={styles.card} onClick={() => navigate("/toefl")}>
          <div className={styles.cardBadge}>NEW FORMAT</div>
          <h2 className={styles.cardTitle}>TOEFL iBT 2026</h2>
          <p className={styles.cardDesc}>
            Aligned with the January 2026 format update. Includes all tasks in
            Reading, Writing, and Speaking.
          </p>
          <ul className={styles.cardList}>
            <li>Reading: Complete the Words / Daily Life / Academic Passage</li>
            <li>
              Writing: Build a Sentence / Write an Email / Academic Discussion
            </li>
            <li>Speaking: Listen &amp; Repeat / Take an Interview</li>
          </ul>
          <Button className={styles.cardBtn}>Start Practice →</Button>
        </div>

        <div className={styles.card} onClick={() => navigate("/toeic")}>
          <h2 className={styles.cardTitle}>TOEIC Reading</h2>
          <p className={styles.cardDesc}>
            Covers all parts of the TOEIC L&amp;R Reading section.
          </p>
          <ul className={styles.cardList}>
            <li>Part 5: Incomplete Sentences (30 questions)</li>
            <li>Part 6: Text Completion (16 questions)</li>
            <li>Part 7: Reading Comprehension (54 questions)</li>
          </ul>
          <Button className={styles.cardBtn}>Start Practice →</Button>
        </div>
      </div>

      <div className={styles.dashboardBar}>
        <Button variant="secondary" onClick={() => navigate("/dashboard")}>
          Dashboard (Score Trends)
        </Button>
      </div>

      <p className={styles.note}>
        Generate questions with an AI agent (for example, Claude Code), and
        save them under <code>public/questions/</code>. Prompt specifications
        for each task are available in <code>public/prompts/</code>.
      </p>
    </div>
  );
}
