#!/usr/bin/env python3
"""
Generate a correct JSON template for TOEFL Reading tasks.

Usage:
    python3 generate-template.py <task>

Available tasks:
    complete-words
    daily-life
    academic

Example:
    python3 generate-template.py daily-life
"""

import json
import sys
from datetime import datetime
from pathlib import Path

TEMPLATES = {
    "complete-words": {
        "paragraph": "TODO: Write the original full paragraph without masking any words.",
        "items": [
            {
                "index": 0,
                "hint": "TODO: first floor(len/2) letters of answer",
                "answer": "TODO: Correct word",
            }
        ],
    },
    "daily-life": {
        "texts": [
            {
                "id": "t1",
                "textType": "email",
                "layout": "email",
                "content": "From: TODO\nTo: TODO\nSubject: TODO\n\nTODO: Email body",
                "questions": [
                    {
                        "id": "q1",
                        "stem": "TODO: Question stem",
                        "options": [
                            "A. Choice A",
                            "B. Choice B",
                            "C. Choice C",
                            "D. Choice D",
                        ],
                        "correctIndex": 0,
                        "type": "factual",
                        "explanation": "TODO: Explanation",
                    }
                ],
            }
        ]
    },
    "academic": {
        "passage": "TODO: Add an academic English passage (around 300-500 words)",
        "questions": [
            {
                "id": "q1",
                "stem": "TODO: Question stem",
                "options": [
                    "A. Choice A",
                    "B. Choice B",
                    "C. Choice C",
                    "D. Choice D",
                ],
                "correctIndex": 0,
                "type": "factual",
                "explanation": "TODO: Explanation",
            }
        ],
    },
}


def get_new_filename(target_dir: Path) -> str:
    """Return a fresh <YYYYMMDD-HHMMSS>.json name. It is the question's
    permanent ID: never rename or reuse it. index.json is generated by Vite."""
    name = f"{datetime.now():%Y%m%d-%H%M%S}.json"
    if (target_dir / name).exists():
        raise SystemExit(f"Error: {name} already exists; retry in a second.")
    return name


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: python3 generate-template.py <task>")
        print("")
        print("Available tasks:")
        print("  complete-words")
        print("  daily-life")
        print("  academic")
        return 1

    task = sys.argv[1]
    if task not in TEMPLATES:
        print(f"Error: Unknown task '{task}'")
        return 1

    # Resolve paths relative to project root (two levels up from this script)
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent.parent.parent.parent
    target_dir = project_root / "public" / "questions" / "toefl" / "reading" / task
    target_dir.mkdir(parents=True, exist_ok=True)

    filename = get_new_filename(target_dir)
    outfile = target_dir / filename

    template = TEMPLATES[task]
    with open(outfile, "w", encoding="utf-8") as f:
        json.dump(template, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Created: {outfile}")
    print("")
    print("Next steps:")
    print(f"  1. Edit {outfile} and replace TODO values with real question content")
    print("  2. Run npm run dev and verify the app behavior")
    return 0


if __name__ == "__main__":
    sys.exit(main())
